from pathlib import Path

import pytest

from discord_codex_bot.config import Config


@pytest.fixture
def config() -> Config:
    return Config(
        discord_token="test-token",
        application_id=123456789012345678,
        allowed_guild_ids=frozenset({111111111111111111}),
        allowed_channel_ids=frozenset({222222222222222222}),
        command_prefix="codex",
        codex_model="gpt-5.6-luna",
        codex_reasoning_effort="high",
        codex_home=Path("/var/lib/codex"),
        codex_workspace=Path("/workspace"),
        codex_workspace_plain=Path("/workspace-plain"),
        codex_timeout_seconds=600,
        max_prompt_chars=6000,
        max_response_chars=12000,
        max_queued_jobs=10,
        attachment_dir=Path("/tmp/discord-codex"),
        max_attachment_bytes=8_000_000,
        max_attachments=4,
        attachment_sweep_minutes=10,
        thread_ttl_minutes=60,
        harvest_interval_minutes=10,
        memory_index_max_lines=200,
        memory_index_max_bytes=25_000,
        memory_user_max_bytes=50_000_000,
        memory_guild_max_bytes=200_000_000,
        memory_read_max_lines=2000,
        memory_read_max_bytes=50_000,
        memory_search_max_matches=50,
        memory_search_context_lines=3,
        memory_recall_rounds=10,
        output_style_path=Path("/opt/discord-codex/output-style.md"),
        permanent_memory_dir=Path("/opt/discord-codex/permanent"),
        agy_home=Path("/home/node"),
        agy_probe_model="gemini-3.8-flash-low",
        agy_settings_path=Path("/opt/discord-codex/agy-settings.json"),
        openrouter_api_key="test-key",
        orcarouter_api_key="test-orca",
        alert_user_id=0,
        alert_after_failures=3,
        alert_cooldown_minutes=30,
        alert_login_check_minutes=60,
        search_url="http://searxng:8080",
        search_api="",
        search_api_key="",
        search_max_results=5,
        remember_emoji_name="114514",
        backup_dir=None,
        backup_hour=3,
        backup_keep_days=14,
        sandbox_url="http://sandbox:8070",
        sandbox_timeout_seconds=30,
        openrouter_dir=Path("/var/lib/codex/openrouter"),
        openrouter_catalog_ttl_seconds=3600,
        openrouter_history_chars=60_000,
        announce_dir=Path("/opt/discord-codex/announce"),
        announce_channel_ids=frozenset(),
        announce_approved="",
        link_max_urls=3,
        link_max_bytes=2_000_000,
        link_max_chars=20_000,
        link_timeout_seconds=15,
        link_render_timeout_seconds=40,
        link_screenshot_max_height=4000,
        link_preview_wait_seconds=2,
        gemini_api_key="test-gemini",
        gemini_model="gemini-flash-latest",
        gemini_timeout_seconds=180,
        gemini_video_inline_max_bytes=12_000_000,
        gemini_video_max_chars=1500,
        video_interim_after_seconds=8,
        consolidate_hour=2,
        consolidate_timezone="Asia/Taipei",
        consolidate_min_remaining_percent=50,
        consolidate_max_input_bytes=100_000,
        consolidate_schema_path=Path("/opt/discord-codex/consolidate-schema.json"),
    )
